---
detectors:
  DataClump:
    min_clump_size: 3
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    public_methods_only: true
exclude_paths:
  - db/migrate
