require:
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.7.2
  Exclude:
    - ".rvm/*"
    - "bin/*"
    - "db/schema.rb"
    - "logs/*"
    - "tmp/**/*"

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Exclude:
    - "app/controllers/application_controller.rb"
    - "app/models/application_record.rb"
    - "config/application.rb"
    - "db/migrate/*"
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
    - "config/routes.rb"
    - "Gemfile"
    - "Rakefile"
    - "spec/**/*"
